services:
  - type: web
    name: socialcirkle-server
    env: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: node dist/index.js
    rootDir: apps/server
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: NODE_ENV
        value: production
